// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywkbobnektngeexfpcnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3a2JvYm5la3RuZ2VleGZwY254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzQ3MjEsImV4cCI6MjA2ODE1MDcyMX0.i4E3PLyOk00RMCS8gZP73lrl4EAd2PxqEAc8C66Kwzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});